# [START django_app]
runtime: python38

network:
  session_affinity: true

handlers:
# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto


includes: 
  - env_variables.yaml


instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.80
  min_instances: 1
  max_instances: 1
# max_pending_latency: 100ms
# max_concurrent_requests: 50

