# Generated by Django 2.2.24 on 2021-09-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='language',
            field=models.IntegerField(choices=[(1, 'ENGLISH'), (2, 'PORTUGUES'), (3, 'ESPANOL')], default=1),
        ),
    ]
