# Generated by Django 2.2.28 on 2022-05-15 22:46

import core.db
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_update', core.db.AutoDateTimeField(default=django.utils.timezone.now)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='favorite_weather_user', to=settings.AUTH_USER_MODEL)),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='weather.Weather')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
